[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://host.docker.internal:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"15.5\", \"appium:deviceName\": \"id/name\", \"appium:automationName\": \"UiAutomator2\"}"
]